@startuml
skinparam monochrome true
skinparam shadowing false
hide footbox

box "Logic" #LightBlue
participant "<<class>>\nParser" as Parser
participant "l:ListCommand" as ListCommand
participant "v:ListCommandValidator" as ListCommandValidator
end box

box "Data" #LightYellow
participant "items:ItemList" as ItemList
participant "categories:CategoryList" as CategoryList
end box

box "UI" #LightGreen
participant "ui:Ui" as Ui
end box

-> Parser : parse("listItems c/Food price high", items, categories, ui, storage)
activate Parser

create ListCommand
Parser -> ListCommand : new ListCommand("listItems c/Food price high")
activate ListCommand
ListCommand --> Parser : l
deactivate ListCommand

Parser -> ListCommand : execute(items, categories, ui)
activate ListCommand

create ListCommandValidator
ListCommand -> ListCommandValidator : new ListCommandValidator("listItems c/Food price high")
activate ListCommandValidator
ListCommandValidator --> ListCommand : v
deactivate ListCommandValidator

ListCommand -> ListCommandValidator : validate(items, categories)
activate ListCommandValidator

ListCommandValidator -> CategoryList : containsCategory("Food")
activate CategoryList
CategoryList --> ListCommandValidator : true
deactivate CategoryList

ListCommandValidator --> ListCommand
deactivate ListCommandValidator
ListCommandValidator -[hidden]-> ListCommand
destroy ListCommandValidator

alt items.isEmpty()
    ListCommand -> Ui : showMessage("Your inventory is empty.")
    activate Ui
    Ui --> ListCommand
    deactivate Ui
else inventory has items
    note right of ListCommand
      Matches regex to extract:
      categoryInput = "Food"
      field = "price"
      order = "high"
    end note

    loop for each item in ItemList
        ListCommand -> ItemList : getItem(i)
        activate ItemList
        ItemList --> ListCommand : item
        deactivate ItemList

        note right of ListCommand: Adds item to local displayList\nif category matches
    end

    opt field and order are present
        note right of ListCommand: displayList.sort() by price in descending order
    end

    ListCommand -> Ui : showMessage("Here are your current inventory items in [FOOD] by price in decreasing order:")
    activate Ui
    Ui --> ListCommand
    deactivate Ui

    loop for each item in displayList
        ListCommand -> Ui : showMessage(listIndex + ". " + item)
        activate Ui
        Ui --> ListCommand
        deactivate Ui
    end
end

ListCommand --> Parser
deactivate ListCommand
ListCommand -[hidden]-> Parser
destroy ListCommand

<-- Parser
deactivate Parser

@enduml