@startuml
skinparam monochrome true
skinparam shadowing false
hide circle
hide footbox


actor User
participant Parser <<class>>
participant ":ShowTransactionHistoryCommand"
participant ":ShowTransactionHistoryCommandValidator"
participant ":TransactionStorage"
participant Ui

User -> Parser: "showHistory"
Parser -> ":ShowTransactionHistoryCommand": create(input, storage)

":ShowTransactionHistoryCommand" -> ":ShowTransactionHistoryCommandValidator": create(input)
":ShowTransactionHistoryCommand" -> ":ShowTransactionHistoryCommandValidator": validate(items, categories)

":ShowTransactionHistoryCommand" -> ":TransactionStorage": load()
":TransactionStorage" --> ":ShowTransactionHistoryCommand": history list

alt history is empty
    ":ShowTransactionHistoryCommand" -> Ui: showMessage("Transaction history is currently empty.")
else
    ":ShowTransactionHistoryCommand" -> Ui: showMessage("Here is your transaction history:")
    loop for each entry
        ":ShowTransactionHistoryCommand" -> Ui: showMessage(formatted receipt card)
    end
end

@enduml